import { QueryProvider } from "../components/provider/query-provider";
import { Provider as ThemeProvider } from "../components/provider/theme-provider";
import { Toaster } from "../components/toast/toast";
import "../styles/global.css";
import { Inter } from "next/font/google";
import SideBarProvider from "../components/provider/side-bar-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head></head>
      <body className={inter.className}>
        <ThemeProvider>
          <SideBarProvider>
            <QueryProvider>{children}</QueryProvider>
          </SideBarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
